name: Surge Auto Update

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Site build
        run: npm run build

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy Site
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: surge ./dist ${{ secrets.DOMAIN }} --token $SURGE_TOKEN
